name: build
on: [push, pull_request]
jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make -C test test test++ elk
  MacOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: make -C test test++ elk upload-coverage
  Windows:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make -C test vc2017 mingw vc22
  ArduinoUno:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make -C test uno
