name: build
on: [push, pull_request]
jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt-get update ; sudo apt-get install valgrind
    - run: make -C test valgrind
    - run: make -C test test test++
    - run: make -C test elk EXTRA_CFLAGS=-DJS_DUMP=1
  MacOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - run: make -C test test++ upload-coverage ARCH_FLAGS=
    - run: make -C test elk ARCH_FLAGS= EXTRA_CFLAGS=-DJS_DUMP=1
  Windows:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: make -C test vc2017 mingw vc22
  ArduinoUno:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: make -C test uno
